[package]
name = "cross-imgui"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27.5"
wgpu = "0.17"
imgui = "0.11"
imgui-winit-support = "0.11"
imgui-wgpu = "0.24"
env_logger = "0.10"
pollster = "0.3"